import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {auth,firebaseConfigured} from "./firebase";
import {createUserWithEmailAndPassword,signInWithEmailAndPassword,sendPasswordResetEmail,signOut,onAuthStateChanged} from "firebase/auth";
import {buildings,equipmentSheets,clientDefault,checklistHeaders,documents} from "./data";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import "./styles.css";

const key=(uid)=>`eifm_records_${uid||"demo"}`;
const load=(uid)=>JSON.parse(localStorage.getItem(key(uid))||"[]");
function Auth({onUser}) {
 const [mode,setMode]=useState("signin"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[err,setErr]=useState("");
 const submit=async e=>{e.preventDefault();setErr("");
  if(!firebaseConfigured){onUser({uid:"demo",email});return}
  try{const r=mode==="signup"?await createUserWithEmailAndPassword(auth,email,password):await signInWithEmailAndPassword(auth,email,password);onUser(r.user)}
  catch(x){setErr(x.message)}
 };
 const reset=async()=>{if(!email)return setErr("Enter your email first.");try{await sendPasswordResetEmail(auth,email);setErr("Password reset email sent.")}catch(x){setErr(x.message)}};
 return <div className="auth"><div className="authcard"><div className="logo"><div className="mark">⌂</div><b>EIFM</b><small>إيفم</small></div><h1>{mode==="signin"?"Login":"Create Account"}</h1><p>Welcome to EIFM WCC & PPM</p>
 <form onSubmit={submit}><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required minLength="6"/>{err&&<div className="error">{err}</div>}
 <button className="primary">{mode==="signin"?"Sign In":"Sign Up"}</button></form>
 {mode==="signin"&&<button className="link" onClick={reset}>Forgot Password?</button>}
 <div className="or">or</div><button className="link" onClick={()=>setMode(mode==="signin"?"signup":"signin")}>{mode==="signin"?"Don't have an account? Sign Up":"Already have an account? Sign In"}</button>
 </div></div>
}
function Checklist({items,setItems}){const add=()=>setItems([...items,{id:Date.now(),task:"",ok:false,notOk:false,remarks:"",follow:""}]);
 return <div><div className="rowbetween"><h3>Checklist</h3><button className="small" onClick={add}>+ Add Task</button></div><div className="tablewrap"><table><thead><tr>{checklistHeaders.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{items.map((r,i)=><tr key={r.id}><td>{i+1}</td><td><input value={r.task} onChange={e=>setItems(items.map(x=>x.id===r.id?{...x,task:e.target.value}:x))}/></td><td><input type="checkbox" checked={r.ok} onChange={e=>setItems(items.map(x=>x.id===r.id?{...x,ok:e.target.checked,notOk:false}:x))}/></td><td><input type="checkbox" checked={r.notOk} onChange={e=>setItems(items.map(x=>x.id===r.id?{...x,notOk:e.target.checked,ok:false}:x))}/></td><td><input value={r.remarks} onChange={e=>setItems(items.map(x=>x.id===r.id?{...x,remarks:e.target.value}:x))}/></td><td><input value={r.follow} onChange={e=>setItems(items.map(x=>x.id===r.id?{...x,follow:e.target.value}:x))}/></td></tr>)}</tbody></table></div></div>}
function App({user}) {
 const [type,setType]=useState("WCC"),[records,setRecords]=useState(()=>load(user.uid)),[building,setBuilding]=useState(""),[project,setProject]=useState(""),[client,setClient]=useState(clientDefault),[wo,setWo]=useState(""),[ppm,setPpm]=useState("1st PPM"),[tel,setTel]=useState(""),[details,setDetails]=useState(""),[date,setDate]=useState(""),[equipment,setEquipment]=useState([]),[checklists,setChecklists]=useState({}),[view,setView]=useState("new"),[search,setSearch]=useState("");
 useEffect(()=>localStorage.setItem(key(user.uid),JSON.stringify(records)),[records,user.uid]);
 const selected=equipment.map(e=>({name:e,rows:checklists[e]||[]}));
 const toggle=e=>{setEquipment(a=>a.includes(e)?a.filter(x=>x!==e):[...a,e]);if(!checklists[e])setChecklists(c=>({...c,[e]:[]}))};
 const save=()=>{const r={id:Date.now(),type,building,project,client,wo,ppm,tel,details,date,equipment,checklists,createdAt:new Date().toISOString()};setRecords([r,...records]);alert("Saved successfully");};
 const exportX=()=>{const rows=records.map(r=>({Type:r.type,Building:r.building,Client:r.client,Project:r.project,"WO Number":r.wo,"PPM":r.ppm,Date:r.date,Equipment:r.equipment.join(", ")}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),"Records");XLSX.writeFile(wb,"EIFM-WCC-PPM-Records.xlsx")};
 const pdf=()=>{const d=new jsPDF();d.setFontSize(16);d.text(type==="WCC"?"WORK COMPLETION CERTIFICATE":"PLANNED PREVENTIVE MAINTENANCE",15,18);d.setFontSize(10);let y=30;[[type==="WCC"?"Job Order Number":"PPM",type==="WCC"?wo:ppm],["Client",client],["Project",project],["Location",building],["Tel. No.",tel],["Date & Time",date]].forEach(([a,b])=>{d.text(`${a}: ${b||""}`,15,y);y+=7});d.text("Details / Checklist:",15,y);y+=7;selected.forEach(s=>{d.text(s.name,15,y);y+=6;s.rows.forEach((x,i)=>{if(y>275){d.addPage();y=20}d.text(`${i+1}. ${x.task}  ${x.ok?"OK":x.notOk?"NOT OK":""}  ${x.remarks}`,18,y);y+=5})});d.text("Signature of Site in Charge: ____________________",15,280);d.save(`${type}-${building||"record"}.pdf`)};
 const filtered=useMemo(()=>records.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())),[records,search]);
 return <div className="app"><header><div className="brand"><span className="mark">⌂</span><b>EIFM</b></div><nav><button className={view==="new"?"active":""} onClick={()=>setView("new")}>New</button><button className={view==="records"?"active":""} onClick={()=>setView("records")}>Saved Records</button></nav><div><span className="email">{user.email}</span><button className="logout" onClick={()=>firebaseConfigured?signOut(auth):location.reload()}>Sign Out</button></div></header>
 {view==="records"?<main><div className="rowbetween"><h2>Saved WCC & PPM Records</h2><button className="small" onClick={exportX}>Export Excel</button></div><input placeholder="Search building, WO, client..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="cards">{filtered.map(r=><div className="record" key={r.id}><b>{r.type} — {r.building}</b><p>Client: {r.client}</p><p>{r.type==="PPM"?r.ppm:`WO: ${r.wo}`}</p><p>Equipment: {r.equipment.join(", ")||"None"}</p><button className="danger" onClick={()=>setRecords(records.filter(x=>x.id!==r.id))}>Delete</button></div>)}</div></main>:
 <main><div className="hero"><h1>{type==="WCC"?"Work Completion Certificate":"Planned Preventive Maintenance"}</h1><p>Professional • Accurate • Efficient</p></div><div className="tabs"><button className={type==="WCC"?"selected":""} onClick={()=>setType("WCC")}>WCC</button><button className={type==="PPM"?"selected":""} onClick={()=>setType("PPM")}>PPM</button></div>
 <section><h2>1. Basic Information</h2><div className="grid"><label>Building / Location<select value={building} onChange={e=>setBuilding(e.target.value)}><option value="">Select building</option>{buildings.map(b=><option key={b}>{b}</option>)}</select></label><label>Client<input value={client} onChange={e=>setClient(e.target.value)}/></label><label>Project<input value={project} onChange={e=>setProject(e.target.value)}/></label><label>{type==="WCC"?"Work Order Number":"PPM Number"}{type==="WCC"?<input value={wo} onChange={e=>setWo(e.target.value)}/>:<select value={ppm} onChange={e=>setPpm(e.target.value)}>{["1st PPM","2nd PPM","3rd PPM","4th PPM"].map(x=><option key={x}>{x}</option>)}</select>}</label><label>Tel. No.<input value={tel} onChange={e=>setTel(e.target.value)}/></label><label>Date & Time<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label></div>{type==="WCC"&&<label>Details of Work / Complaint<textarea rows="6" value={details} onChange={e=>setDetails(e.target.value)} placeholder={"Example: One spotlight not working\nComplaint / work details..."}/></label>}</section>
 <section><h2>2. Manually Add Equipment / Checklist</h2><p className="muted">Building select karne ke baad sirf required equipment manually add karein. Kuch bhi automatic force nahi hoga.</p><div className="equip">{equipmentSheets.map(e=><button key={e} className={equipment.includes(e)?"chosen":""} onClick={()=>toggle(e)}>{equipment.includes(e)?"✓ ":""}{e}</button>)}</div>{selected.map(s=><div className="check" key={s.name}><h3>{s.name}</h3><Checklist items={s.rows} setItems={rows=>setChecklists(c=>({...c,[s.name]:rows}))}/></div>)}</section>
 <section><h2>3. Signatures</h2><div className="signgrid"><div>Signature of Site in Charge<div className="signature"></div>Name: __________ Date: __________ ID: __________</div><div>Signature of HOD<div className="signature"></div>Name: __________ Date: __________ ID: __________</div><div>Client Signature<div className="signature"></div>Name: __________ Phone: __________ Date: __________</div></div></section>
 {type==="WCC"&&<section><h2>4. Enclosed Documents</h2><div className="docs">{documents.map(d=><label key={d}><input type="checkbox"/>{d}</label>)}</div><p>Dear valued customer, please mark your satisfaction level: 1. Poor  2. Satisfied  3. Good  4. Very Good  5. Excellent</p><textarea placeholder="Remarks / Suggestions" rows="3"/></section>}
 <div className="actions"><button className="primary" onClick={save}>Save {type}</button><button className="secondary" onClick={pdf}>Export PDF</button></div></main>}</div>
}
function Root(){const [user,setUser]=useState(null);useEffect(()=>{if(firebaseConfigured)return onAuthStateChanged(auth,setUser)},[]);if(!user)return <Auth onUser={setUser}/>;return <App user={user}/>}
createRoot(document.getElementById("root")).render(<Root/>);