workflows:
  eifm-android:
    name: EIFM Android APK
    max_build_duration: 20
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - name: Create base Flutter project if missing
        script: |
          if [ ! -d "android" ]; then
            flutter create --platforms=android .
          fi

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build Android APK (Debug)
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      
